#!/usr/bin/env ruby

$LOAD_PATH << ".git/hooks"

require 'lib/commit_info_git.rb'
require 'tests/message_test.rb'

message_test = MessageTest.new

File.open(ARGV[0], "r") do |file|
    commit_info = CommitInfoGit.new
    commit_info.commit_message = file.read()
    
    message_test.perform(commit_info);
end

if message_test.success?
    exit 0
else
    exit 1
end
