#!/usr/bin/env ruby

$LOAD_PATH << ".git/hooks"

require 'lib/commit_info_git.rb'
require 'tests/copy_test.rb'
require 'tests/space_test.rb'

commit_info = CommitInfoGit.new

tests = []

tests << CopyTest.new
tests << SpaceTest.new

passed = true

tests.each do |test|
    test.perform(commit_info)
    if not test.success?
        passed = false
    end
end

exit passed ? 0 : 1
